<?php
declare(strict_types=1);

namespace Survos\DataBundle\Command;

use Survos\DataContracts\Vocabulary\Core;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\String\Inflector\EnglishInflector;
use Symfony\Component\Yaml\Yaml;

/**
 * Dump system UI strings into the `system` translation domain so the app can `|trans(domain: 'system')`
 * them — starting with the folio core codes, which otherwise render as raw `obj`/`per`/`coll`.
 *
 * Modernized port of the deprecated `app:translate-system` (mus): same idea — generate a source
 * catalog of system strings — but sourced from the canonical {@see Core} vocab (constant name = English
 * label) instead of the old Pixie/AppService coupling, and written as a plain Symfony catalog.
 *
 * This builds the **English source** only. Per-locale machine translation (the old LibreTranslate path)
 * is the lingua-bundle seam, wired separately later; for now translate the generated EN file by hand or
 * via lingua into system+intl-icu.<locale>.yaml.
 */
#[AsCommand('trans:system', 'Build the EN "system" translation catalog (folio core labels) for |trans(domain: "system")')]
final class SystemTranslateCommand
{
    public function __construct(
        #[Autowire('%kernel.project_dir%/translations')]
        private readonly string $translationDir,
        private readonly Filesystem $filesystem = new Filesystem(),
    ) {
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Option('Overwrite even if the catalog already exists')]
        bool $force = false,
    ): int {
        $inflector = new EnglishInflector();

        // Core constant NAME is the English singular (OBJECT → Object); the code is the catalog key
        // suffix (core.obj). Provide a plural (headings/lists) and a singular (.one) per core.
        $keys = [];
        foreach ((new \ReflectionClass(Core::class))->getConstants() as $name => $code) {
            if (!is_string($code) || $code === '') {
                continue;
            }
            $singular = ucfirst(strtolower($name));
            $plural = $inflector->pluralize($singular)[0] ?? $singular;
            $keys['core.' . $code] = $plural;
            $keys['core.' . $code . '.one'] = $singular;
        }
        ksort($keys);

        $file = $this->translationDir . '/system+intl-icu.en.yaml';
        if (is_file($file) && !$force) {
            $io->warning(sprintf('%s exists; re-run with --force to overwrite.', $file));
            $io->listing(array_map(fn($k, $v) => "$k: $v", array_keys($keys), $keys));
            return Command::SUCCESS;
        }

        $this->filesystem->dumpFile(
            $file,
            "# Generated by `bin/console trans:system`. English source for the 'system' domain.\n"
            . "# Per-locale translation (system+intl-icu.<locale>.yaml) is the lingua-bundle seam — TODO.\n\n"
            . Yaml::dump($keys),
        );

        $io->success(sprintf('Wrote %d system string(s) → %s', count($keys), $file));
        $io->note("Use it: {{ ('core.' ~ core.code)|trans({}, 'system') }}");

        return Command::SUCCESS;
    }
}
